services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  # prod:
  #   build: .
  #   ports:
  #     - "8001:8000"
  #   command: gunicorn config.wsgi:application --bind 0.0.0.0:8000