# Generated by Django 6.0.5 on 2026-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.CharField(blank=True, choices=[('out', 'out'), ('home', 'home'), ('computer', 'computer')], max_length=25),
        ),
    ]
