# Generated by Django 6.0.5 on 2026-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_task_task_id_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.CharField(choices=[('---', '---'), ('out|side', 'out|side'), ('home', 'home'), ('office', 'office'), ('computer', 'computer')], default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
